# Generated by Django 4.2.3 on 2023-07-29 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='online_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='chatroom_online_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
