# Generated by Django 4.2.3 on 2023-07-10 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_message_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chatroom_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='online_users',
            field=models.ManyToManyField(related_name='chatroom_online_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
